language: generic
sudo: required
services:
 - docker
before_install:
 - docker build -t yaelgalifat/docker-react -f Dockerfile.dev .
script:
 - docker run -e CI=true yaelgalifat/docker-react npm run test
